"""'added_tables'

Revision ID: 425d0deda945
Revises: 
Create Date: 2020-05-16 14:24:30.001860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425d0deda945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_name', sa.Text(), nullable=True),
    sa.Column('dev_room', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_status', sa.Text(), nullable=True),
    sa.Column('time_stamp', sa.Text(), nullable=True),
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dev_id'], ['Device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Action')
    op.drop_table('Device')
    # ### end Alembic commands ###
